### ISSUE TITLE
Se debe trabajar las variables como propiedades, para que obtengan y coloquen valores ( get; set; )

### ISSUE THREAD

**Issue by DjMarte** [Cape23180909/RegistroTecnicos#3]
https://github.com/Cape23180909/RegistroTecnicos/blob/056bb9d84f92bf980be507221e52a9538a1b78b3/RegistroTecnicos/Components/Pages/Tecnicospages/Index.razor#L57-L58

**Comment by Cape23180909** [comment]
Corregido
