### ISSUE TITLE
#1 Te falta Ponerle el simbolo de Interogacion en  para que nunca sea nula

### ISSUE THREAD

**Issue by jose12rivera** [Cape23180909/RegistroTecnicos#7]
https://github.com/Cape23180909/RegistroTecnicos/blob/404572f51cd3c587dfb5dac189b470b7c6313cf5/RegistroTecnicos/Components/Pages/Prioridadespages/Create.razor#L47

**Comment by Cape23180909** [comment]
Corregido "Se me olvido colocar el nombre del issus, pero la correccion de este es el comit 217
